<?php

namespace CC\PlaysureBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BetRepository extends EntityRepository
{
	public function getbet($betId)
	{
		$betRepository = $this->getEntityManager()->getRepository('CCPlaysureBundle:Expert');
		$bet = $expertRepository->find($betId);
		return $bet;
	}
	public function getBetsByUserId($userId)
	{
		$betRepository = $this->getEntityManager()->getRepository('CCPlaysureBundle:Bet');
		$bets = $betRepository->findByUserId($userId, array('id' => 'DESC'));
		return $bets;		
	}

}
