<?php

namespace CC\PlaysureBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ExpertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExpertRepository extends EntityRepository
{
}
