<?php

namespace CC\PlaysureBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ExpertBetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExpertBetRepository extends EntityRepository
{
}
