<?php

namespace CC\PlaysureBundle\Entity;

use Doctrine\ORM\EntityRepository;

use CC\PlaysureBundle\Entity\ExpertBet;
use CC\PlaysureBundle\Entity\ExpertBetRepository;

/**
 * ExpertBetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExpertBetRepository extends EntityRepository
{

	public function getExpertBets($expertId)
	{
		$expertRepository = $this->getEntityManager()->getRepository('CCPlaysureBundle:ExpertBet');
		$expertBets = $expertRepository->findByExpertId($expertId);
		return $expertBets;
	}
}
