<?php

namespace CC\PlaysureBundle\Entity;

use Doctrine\ORM\EntityRepository;

use CC\PlaysureBundle\Entity\Expert;
use CC\PlaysureBundle\Entity\ExpertRepository;

/**
 * ExpertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExpertRepository extends EntityRepository
{


	public function getExpert($expertId)
	{
		$expertRepository = $this->getEntityManager()->getRepository('CCPlaysureBundle:Expert');
		$expert = $expertRepository->find($expertId);
		return $expert;
	}

}
