<?php

namespace CC\PlaysureBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PastBetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PastBetRepository extends EntityRepository
{
	public function getpastBets($expertId)
	{
		$pastBetRepository = $this->getEntityManager()->getRepository('CCPlaysureBundle:PastBet');
		$pastBets = $pastBetRepository->findByExpertId($expertId);
		return $pastBets;
	}
}
