cc_hello_name:
    path:     /hello/{name}
    defaults: { _controller: CCPlaysureBundle:Home:hello }

home:
    path:     /
    defaults: { _controller: CCPlaysureBundle:Home:index }

submit_new_game:
    path:     /submitnewgame
    defaults: { _controller: CCPlaysureBundle:Game:submitNewGame }

admin:
    path:     /admin
    defaults: { _controller: CCPlaysureBundle:Admin:index }

betOnGame:
    path:     /betongame/{gameId}
    defaults: { _controller: CCPlaysureBundle:Game:betOnGame }

createNewExpert:
    path:     /createnewexpert
    defaults: { _controller: CCPlaysureBundle:Admin:createNewExpert }