cc_hello_name:
    path:     /hello/{name}
    defaults: { _controller: CCPlaysureBundle:Home:hello }

home:
    path:     /
    defaults: { _controller: CCPlaysureBundle:Home:index }

submit_new_game:
    path:     /submitnewgame
    defaults: { _controller: CCPlaysureBundle:Game:submitNewGame }

admin:
    path:     /admin
    defaults: { _controller: CCPlaysureBundle:Admin:index }

gameView:
    path:     /game/{gameId}
    defaults: { _controller: CCPlaysureBundle:Game:gameView }

createNewExpert:
    path:     /createnewexpert
    defaults: { _controller: CCPlaysureBundle:Admin:createNewExpert }

createNewExpertBet:
    path:     /createnewexpertbet
    defaults: { _controller: CCPlaysureBundle:Admin:createNewExpertBet }

ajaxTest:
    path:     /testajax
    defaults: { _controller: CCPlaysureBundle:Admin:ajaxTest }