cc_hello_name:
    path:     /hello/{name}
    defaults: { _controller: CCPlaysureBundle:Home:hello }

home:
    path:     /
    defaults: { _controller: CCPlaysureBundle:Home:index }

submit_new_game:
    path:     /submitnewgame
    defaults: { _controller: CCPlaysureBundle:Game:submitNewGame }